//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sdpEntities : DbContext
    {
        public sdpEntities()
            : base("name=sdpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DeliveryNote> DeliveryNotes { get; set; }
        public virtual DbSet<InstallationNote> InstallationNotes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<PurchaseList> PurchaseLists { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<RetailStore> RetailStores { get; set; }
        public virtual DbSet<SalesOrderDefect> SalesOrderDefects { get; set; }
        public virtual DbSet<SalesOrderInfo> SalesOrderInfoes { get; set; }
        public virtual DbSet<SalesOrderProduct> SalesOrderProducts { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Van> Vans { get; set; }
    }
}
