//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryNote
    {
        public int deliveryID { get; set; }
        public Nullable<int> orderNo { get; set; }
        public Nullable<int> staff_id { get; set; }
        public string staff_name { get; set; }
        public string vehicleNo { get; set; }
        public string deliverySession { get; set; }
        public bool isDelivered { get; set; }
        public string cus_name { get; set; }
        public string cus_address { get; set; }
        public Nullable<int> cus_phone { get; set; }
        public Nullable<System.DateTime> deliveryDate2 { get; set; }
    
        public virtual Van Van { get; set; }
    }
}
