//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallationNote
    {
        public int installationID { get; set; }
        public Nullable<int> orderNo { get; set; }
        public int staffID { get; set; }
        public string installSession { get; set; }
        public Nullable<bool> isInstalled { get; set; }
        public Nullable<System.DateTime> installDate { get; set; }
        public string cusPhone { get; set; }
    }
}
