//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.SalesOrderProducts = new HashSet<SalesOrderProduct>();
            this.SalesOrderDefects = new HashSet<SalesOrderDefect>();
        }
    
        public int productID { get; set; }
        public int supplierID { get; set; }
        public int categoryID { get; set; }
        public string productName { get; set; }
        public string model { get; set; }
        public double price { get; set; }
        public int quantity { get; set; }
        public bool active { get; set; }
        public Nullable<int> reorderLevel { get; set; }
        public int retailID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderProduct> SalesOrderProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderDefect> SalesOrderDefects { get; set; }
    }
}
