//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int purchaseID { get; set; }
        public System.DateTime orderDate { get; set; }
        public double total { get; set; }
        public bool approval { get; set; }
        public bool orderStatus { get; set; }
        public bool orderChecked { get; set; }
        public string remark { get; set; }
        public bool isClaimed { get; set; }
    }
}
