//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailStore
    {
        public int retailID { get; set; }
        public string location { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public bool isWareHouse { get; set; }
    }
}
