//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int staff_id { get; set; }
        public string staff_password { get; set; }
        public string staff_name { get; set; }
        public string staff_email { get; set; }
        public string staff_access { get; set; }
        public Nullable<bool> active { get; set; }
        public int retailID { get; set; }
    }
}
